---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r, echo=FALSE}
if (!require("gifski", quietly=TRUE)) install.packages("gifski")
depth = 15
```

# Sierpiński triangle

> The **Sierpinski triangle** (also with the original orthography Sierpiński), also called the **Sierpinski gasket** or **Sierpinski sieve**, is a fractal attractive fixed set with the overall shape of an equilateral triangle, subdivided recursively into smaller equilateral triangles.

```{r}

generateSierpinski <- function(rows) {
  # generate the rows and return them
  mat = matrix(0, nrow = rows, ncol = 2)
  colnames(mat) = c("x", "y")

    for (i in seq_len(rows - 1)) {
    vertex = sampleVertex(3)
    point = mat[i, ]
    next.point = stepToVertex(point, vertex, 0.5)
    mat[i + 1, ] = next.point
  }
  mat
}

# Sample a Vertex of the n-Gon with base (0, 0) -> (1, 0)
# n: number of vertices (e.g. n=3: Triangle)
# Return a vector of length 2 with x and y coordinates
sampleVertex <- function(n) {
  midpoint = c(x=0.5, y=0.5 / tan(pi / n))
  radius = 0.5 / sin(pi / n)
  angle = 2 * pi / n * (sample(n, 1))

  midpoint + radius * c(sin(angle), cos(angle))
}

# Create a point that is a step from `from` to `to`
# step.size is a number between 0 and 1, indicating
#   the relative weight of `from` and `to`.
#   * step.size = 0 --> stay at `from`
#   * step.size = 1 --> end up at `to`
#   * step.size = 0.5 --> halfway between `from` and `to`
stepToVertex <- function(from, to, step.size) {
  from * (1 - step.size) + to * step.size
}
sierpinski.df <- generateSierpinski(rows = 2^depth)
```

```{r, animation.hook="gifski", interval = 0.2, fig.asp=sqrt(0.75)}
par(mar=c(0.2, 0.2, 1.5, 0.2))
for (draw.depth in seq(1, 2^depth, length = 20)) {
  plot(sierpinski.df[seq_len(draw.depth), ],
       ylim=c(0, sqrt(.75)), xlim=c(0, 1), pch=".",
       xlab="", ylab="", xaxt="n", yaxt="n",
       main="Sierpinski Triangle")
}
```
